baseURL = "https://www.jamesmoriarty.xyz/"
languageCode = "en-us"
title = "James Moriarty"
theme = "soho"
summarylength = 10
enableEmoji = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    noClasses = true
    style = "github"

[params]
author = "James Moriarty"
description = ""
customCss = [ "css/custom.css" ]

## Set one of:
# gravatar = "jamespaulmoriarty@gmail.com"
profilePicture = "images/james-moriarty.jpg"

copyright = "James Moriarty"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#313131"

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/jamespaulmoriarty"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/jamesmoriarty"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/jamespmoriarty"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Talks"
  weight = 300
  identifier = "talks"
  url = "/talks/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 400
  url = "/about/"

  [[menu.main]]
  name = "Diving"
  weight = 500
  identifier = "diving"
  url = "/diving/"

  [[menu.main]]
  name = "Software"
  weight = 800
  identifier = "software"
  url = "/software/"

  [[menu.main]]
  name = "Hardware"
  weight = 900
  identifier = "hardware"
  url = "/hardware/"